### ISSUE TITLE
Any chance that the telecope picker could be a color scheme, too?`

### ISSUE THREAD

**Issue by emilBeBri** [scottmckendry/cyberdream.nvim#10]
Hi so I love this theme, thank you. I  also really like the telescope picker colors, I find that black is perfectly black without being 'one hundred percent black', and the red and green for 'find' files' and 'files preview' are perfectly matched to it, too. I can't help but wonder if that would be a good color theme in it's own right, of course with some other colors of the same hue thrown in, too? Just a thought, sorry if this is not the place for it. And I really like the color schemehere, too!

**Comment by scottmckendry** [comment]
Thanks for the feedback! I'm glad you like the colorscheme. 

The telescope theming was something I transplanted over from my personal neovim configuration. Feel free to take a look at [this commit](https://github.com/scottmckendry/Windots/blob/2e7084429f9b3d1e9f5972d190118ea7e2076f80/nvim/lua/plugins/telescope.lua) to see how it can be implemented (and customised to your liking).

If you're after the specific colors I'm using in cyberdream, they can all be found in [colors.lua](https://github.com/scottmckendry/cyberdream.nvim/blob/main/lua/cyberdream/colors.lua). The background for telescope is `bgalt`.

Hope this helps!

**Comment by emilBeBri** [comment]
It does, thanks 😊
