### ISSUE TITLE
Inaccurate colors for certain words inside comments

### ISSUE THREAD

**Issue by josevelaz** [scottmckendry/cyberdream.nvim#103]
### Description

![CleanShot 2024-07-26 at 13 09 55@2x](https://github.com/user-attachments/assets/48659c64-9048-49c7-90a8-7f8618d33448)

Looks like some keywords inside comments are being highlighted

### Neovim version?

10

### What should happen?

Comments should all be the same color

### What happened instead?

Certain keywords are colored inside comments

### Your configuration

```Lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            borderless_telescope = false,
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

**Comment by scottmckendry** [comment]
Hi @josevelaz! These highlights are from neovim built in spell checker. You can turn them off with `:set nospell`

Personally I only have spell check enabled on certain file types. You can read more about **Spell** here:

https://neovim.io/doc/user/spell.html

Hope this helps!

**Comment by josevelaz** [comment]
@scottmckendry That fixed it.
Somewhat odd though that it wasn't displaying a diagnostic message for some files but it was for others. But it seems unrelated. I guess i never noticed the issue with cattpuccin since it only colors the underline and not the word.

**Comment by scottmckendry** [comment]
I thought about it, and what you are saying makes a lot of sense. The fg highlight is unnecessary when combined with the under curl.

I've updated the groups so only the under curl is highlighted — that way the fg can be set dynamically depending on the misspelt token.
