### ISSUE TITLE
how to change line number color ?

### ISSUE THREAD

**Issue by zackAJ** [scottmckendry/cyberdream.nvim#119]
### Question or Suggestion

I want to change the line number color, along with the git blame text.
I'm guessing that it's not handled by this theme ?

**Comment by scottmckendry** [comment]
Hello @zackAJ!

> I'm guessing that it's not handled by this theme ?

There's a very good chance it is! Can you send through a screenshot or something that shows exactly what you want to change?
I'm assuming you're also using a plugin for git blame? If so, can you share the details/config with me so I can have a play around? 

Cheers! 🙂

**Comment by zackAJ** [comment]
thank you for the quicky @scottmckendry
I managed to change the line number colors as follow

```lua
local colors = require("cyberdream.colors")
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = colors.default.cyan })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.default.green })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = colors.default.cyan })
```
this is how it looks now:
![image](https://github.com/user-attachments/assets/39090dad-b2f4-4de1-a1a1-5f723e556b0d)

now I'm trying to change the git blame text color next, it's produced by gitsigns (see the right side blame text)
![image](https://github.com/user-attachments/assets/7a71774c-c1ee-4b1a-86dd-afb35a2ce3ed)

it looks like I'll be able to do something similar to the above solution, I'll keep u updated.
thank you for good work.

**Comment by zackAJ** [comment]
@scottmckendry solved:
```lua
local colors = require("cyberdream.colors").default
vim.api.nvim_set_hl(0, "LineNrAbove", { fg = colors.cyan })
vim.api.nvim_set_hl(0, "LineNr", { fg = colors.green })
vim.api.nvim_set_hl(0, "LineNrBelow", { fg = colors.cyan })
vim.api.nvim_set_hl(0, "GitSignsCurrentLineBlame", { fg = colors.cyan })

```

**Comment by scottmckendry** [comment]
Glad I could help! 😉 

Just a note RE your config, you can do this via an overrides function as shown in the example below:

```lua
return {
    "scottmckendry/cyberdream.nvim",
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            theme = {
                overrides = function(colors)
                    return {
                        LineNrAbove = { fg = colors.cyan },
                        LineNr = { fg = colors.cyan },
                        LineNrBelow = { fg = colors.cyan },
                        GitSignsCurrentLineBlame = { fg = colors.cyan },
                    }
                end,
            },
        })

        vim.cmd("colorscheme cyberdream")
    end,
}
```

This is the way we intend users to configure their overrides, and it makes it a bit more reliable if you plan to use light/dark toggling and other advanced features we may or may not add in the future.

That being said, there's nothing wrong with the way you've pulled it off! Enjoy 🙂

**Comment by zackAJ** [comment]
that's much cleaner, thank you for the help :)
