### ISSUE TITLE
Heirline support?

### ISSUE THREAD

**Issue by agoodfellow123** [scottmckendry/cyberdream.nvim#12]
Hello there, your theme works well with most of the heirline components actually but there is one that caught my eye, the mode indicators does not change color with this theme, I tired to implement it myself but I clearly don't know what I'm doing :)

**Comment by scottmckendry** [comment]
Thanks for raising! I've not used hierline before but from a quick look at the docs, I can see that the configuration is quite verbose (including setting your own highlights). 

Would you mind sharing your config here? I think it would be a good starting point before I get too far down the rabbit hole 😁

Have you had positive results with other colorshemes at all? That might also be helpful to our cause.

Cheers!

**Comment by agoodfellow123** [comment]
Hello! It seems at a raging moment yesterday I have deleted everything I have done so far, It was all in this file and I can't find it anymore...

https://github.com/agoodfellow123/NEON/blob/main/lua/plugins/2-z-ui.lua

My suggestion would be to look at line 169 in that file since it was the only color option hairline accepted with cyberdream. Rest was simply ignored (the ones that are supposed to be called with `hl.mode_colors`)

**Comment by agoodfellow123** [comment]
There is another problem I forgot to mention, despite me specifically setting heirline components colors to black by:
```
               StatusLine = { fg = "#ffffff", bg = "#000000" },
               TabLine = { fg = "#7b8496", bg = "#000000" },
               TabLineFill = { fg = "#7b8496", bg = "#000000" },
               FoldColumn = { fg = "#7b8496", bg = "#000000" },
```
Or typing just `"black"` they cannot get transparent in terminal.

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/36235265/3da7cbea-cbdc-4724-9c1b-51d0de9b048e)

**Comment by scottmckendry** [comment]
@agoodfellow123 I think I've resolved this now but will wait for confirmation before I close.

Status and tabline highlights should also look a bit better by default now, so you can remove your highlight overrides. Just so you're aware, to make a highlight transparent, its value should be `"NONE"` e.g.:

```lua
StatusLine = { fg = "#ffffff", bg = "NONE" }
```

Let me know how you get on 🙂

**Comment by scottmckendry** [comment]
Just to add to this, I'd suggest going back to the [original NormalNvim config for Heirline](https://github.com/NormalNvim/NormalNvim/blob/e909ca7eaee571a17843dd3fe45fb0fe4a7de34d/lua/plugins/2-ui.lua#L291-L385) as a starting point, then add back your changes one at a time (if all looks good).

**Comment by agoodfellow123** [comment]
Thank you for the solution! Terminal problem is completely fixed now!
As for the backgrounds of the modes... Well I did try the original config but unfortunately, it still shows up as black only.

**Comment by scottmckendry** [comment]
It _should_ be working now. After a bit of head-scratching, it appeared I'd misread the [highlight configuration](https://github.com/Zeioth/heirline-components.nvim/blob/1da1a9036e4ca2cfc5e1a61a12de3254b0104347/lua/heirline-components/core/hl.lua#L151-L164) in heirline-components.nvim. 

Turns out I was setting the foreground instead of the background. I've also fixed the winbar highlights too. Looks like it was getting the same black bar that you showed in an earlier screenshot.

Let me know if everything looks okay now.

**Comment by agoodfellow123** [comment]
Yup! That's it! Thanks!

As a side question (which is not related to this project), since you mingled with the code do you know how can I change the colors (or the text)? I have the following script but it is getting ignored:

```
          mode_colors = {
            n = "red" ,
            i = "green",
            v = "cyan",
            V =  "cyan",
            ["\22"] =  "cyan",
            c =  "orange",
            s =  "purple",
            S =  "purple",
            ["\19"] =  "purple",
            R =  "orange",
            r =  "orange",
            ["!"] =  "red",
            t =  "red",
            },
          }),
```

**Comment by scottmckendry** [comment]
Not sure how best to get that working in the heirline config... However, you can override the newly added highlight groups to your liking directly in your cyberdream config.

It might look something like this:

```lua
{
    "scottmckendry/cyberdream.nvim",
    config = function()
        local colors = require("cyberdream.colors").default -- Import the default cyberdream colors
        require("cyberdream").setup({
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,

            theme = {
                -- Override highlights to your liking :)
                highlights = {
                    HeirlineInactive = { bg = colors.grey },
                    HeirlineNormal = { bg = colors.red },
                    HeirlineVisual = { bg = colors.cyan },
                    HeirlineReplace = { bg = colors.orange },
                    HeirlineCommand = { bg = colors.orange },
                    HeirlineInsert = { bg = colors.green },
                    HeirlineTerminal = { bg = colors.red },
                },
            },
        })
        vim.cmd("colorscheme cyberdream")
    end,
},
```
If you need to check which colors are available in the default theme, you can find them here:
https://github.com/scottmckendry/cyberdream.nvim/blob/main/lua/cyberdream/colors.lua

Hex codes also work, if you want an entirely new color. 

P.S. I realised I missed one of the highlight groups while I was writing this (HeirlineTerminal), so I've added that too in the latest commit.

**Comment by agoodfellow123** [comment]
Thank you!... Right umm I added these lines to their correct places and this happened:

```
HeirlineInactive = { bg = "#222222" },
HeirlineNormal = { bg = "#040040" },
HeirlineVisual = { bg = "#003c40" },
HeirlineReplace = { bg = "004028" },
HeirlineCommand = { bg = "004028" },
HeirlineInsert = { bg = "390040" },
HeirlineTerminal = { bg = "400000" },
```

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/36235265/19a40669-6c7f-428b-a830-5002176cb304)

Can't say this was the look I was going for but the second time I launched it just gave an error about cyberdream not being loaded which was weird because it was working as intended, minus hairline colors. For now I just removed them.  And yes cyberdream is up to date.

**Comment by scottmckendry** [comment]
As a guess, I'd say there's an error in the cyberdream spec that's preventing it from being loaded. If, you copied my example verbatim, it might not work in the context of NomalNvim. Or it could just be a missing comma/parenthesis etc.

**Comment by agoodfellow123** [comment]
Ah you are right! i forgot the # before hex values on some lines. Thank you.
