### ISSUE TITLE
Transparency for fzf-lua.

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#120]
### Question or Suggestion

Hi scottmckendry. Can transparency for fzf-lua be considered in the transparent mode. It would be really cool if that can be done.

**Comment by scottmckendry** [comment]
@231tr0n this should now be supported. Fzf lua will now respect the `borderless_telescope` setting. Set to `false` to get a fully-transparent fzflua window 🙂
