### ISSUE TITLE
Include the @variable.member and @lsp.type.property treesitter highlight groups as defaults

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#121]
### Question or Suggestion

Hi scottmckendry! 
I think you addressed these highlight groups in this issue https://github.com/scottmckendry/cyberdream.nvim/issues/84#issue-2380043294.
I just wanted to know if these two highlight groups can be added as defaults for treesitter instead of me overriding it since they seem to play an import role in languages like lua and javascript.
These are the below treesitter highlights.
```lua
overrides = function(colors)
	return {
		["@variable.member"] = { fg = colors.pink },
		["@lsp.type.property"] = { fg = colors.pink },
	}
end,
```
This changes a lot and the colorscheme looks a lot better with this highlights for languages like lua and js
![image](https://github.com/user-attachments/assets/c7771654-bd40-4721-9f55-235eb79ccba5)
![image](https://github.com/user-attachments/assets/7926c2fc-3a79-4ddf-8555-24b9e7a01619)

**Comment by scottmckendry** [comment]
It's definitely a change that I _could_ make. However, what seems like important syntax to one person may be entirely undesirable to another. 

If I make this change so you can remove your overrides, someone else who prefers the current default (like me 😉) will need to do the opposite.

Hopefully, this makes sense.
