### ISSUE TITLE
Support for OXY2DEV/helpview.nvim

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#122]
### Question or Suggestion

Hi scottmckendry! Can support for this plugin be included as part of cyberdream.nvim. It would be really helpful if this could be included.
https://github.com/OXY2DEV/helpview.nvim

**Comment by scottmckendry** [comment]
@231tr0n support has been added in the latest commit and will be included in the 3.9.0 release.

There is currently a problem I'm facing with links not accepting my overrides which I've raised [here](https://github.com/OXY2DEV/helpview.nvim/issues/7). Once that's resolved it should all look quite cohesive!

Cheers!
