### ISSUE TITLE
Support for OXY2DEV/markview.nvim

### ISSUE THREAD

**Issue by OXY2DEV** [scottmckendry/cyberdream.nvim#127]
### Suggestion

Hi, @scottmckendry. Can you add support for [OXY2DEV/markview.nvim](https://github.com/OXY2DEV/markview.nvim)?

By default, the plugin currently looks like this.

![Screenshot_2024-08-21-20-31-49-434_com termux-edit](https://github.com/user-attachments/assets/3c217eb5-8e35-4f40-9391-292b5c4b19ca)
<sub>Dark mode</sub>

![Screenshot_2024-08-21-20-32-49-189_com termux-edit (1)](https://github.com/user-attachments/assets/dd63dc52-cb8b-468b-a8fb-ca881ec42d65)
<sub>Light mode</sub>

Unfortunately, I have no idea how much of the `colorscheme` is respected by it(since I can't actually test it with transparent background). So, it would be great if you could add support for this plugin.

You can find all the [highlight groups here](https://github.com/OXY2DEV/markview.nvim?tab=readme-ov-file#-highlight-groups).

**Comment by scottmckendry** [comment]
Thanks @OXY2DEV,

I've updated the existing extension with the new highlight group names. I can also confirm that transparency works as expected 🙂
