### ISSUE TITLE
Add Highlights for StatusCol

### ISSUE THREAD

**Issue by niksingh710** [scottmckendry/cyberdream.nvim#13]
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/60490474/8b558126-1c85-4ae9-a596-9dcaeded3f5c)

**Comment by scottmckendry** [comment]
Could you share both your cyberdream.nvim and statuscol.nvim configs? Thank you 🙂

**Comment by scottmckendry** [comment]
@niksingh710 found your config and copied it, looks much better now on the latest commit 👍🏻

**Comment by niksingh710** [comment]
Now this looks sexy!! Ty for the quick fix.
