### ISSUE TITLE
Stylix template

### ISSUE THREAD

**Issue by bmoore01** [scottmckendry/cyberdream.nvim#133]
### Question or Suggestion

Hey is it possible to also make this into a stylix template? 
https://github.com/danth/stylix

Would be nice to be able to theme the whole OS with this theme!

**Comment by scottmckendry** [comment]
Hi @bmoore01!

I'm not using Nix or Home Manager currently. But this sounds like a cool idea, and I'd be happy to merge a PR. 
After skimming the [docs](https://stylix.danth.me/configuration.html#extending), looks like we need to generate something in the base16 format. 

We could potentially use the pywal theme [here](https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/pywal/cyberdream.json) as a starting point.

There are instructions for creating extras in the contributing guide here:
https://github.com/scottmckendry/cyberdream.nvim/blob/main/CONTRIBUTING.md#adding-extras-

Happy to answer any questions!

**Comment by scottmckendry** [comment]
@bmoore01 take a look here 🙂 
https://github.com/scottmckendry/cyberdream.nvim/tree/main/extras/base16

Let me know how it goes.
