### ISSUE TITLE
overrides is not called

### ISSUE THREAD

**Issue by OliverGuy** [scottmckendry/cyberdream.nvim#134]
### Description

Greetings, love the theme!
Just trying to switch color around to get closer to my old vscode setup :smile:
When using `overrides(colors)` in the setup options, the function does not seem to get called.

### Neovim version?

0.10.1

### What should happen?

Expected functions to be yellow, or at least the debug message 'Overriding!' to be printed.

### What happened instead?

Functions are still blue, and no message was printed.

### Your configuration

```Lua
{
   'scottmckendry/cyberdream.nvim',
    priority = 1000,
    lazy = false,
    init = function()
      vim.g.colors_name = 'cyberdream'
      vim.cmd.colorscheme 'cyberdream'
    end,
    opts = {
      transparent = false,
      borderless_telescope = false,
      overrides = function(colors)

        print 'Overriding!'

        local highlights = {
          Function = { fg = colors.yellow },
        }
        return highlights
      end,
    },
}
```

**Comment by scottmckendry** [comment]
Oh, never mind! I think i've spotted the problem.

`overrides` is a child property of `theme` e.g.

```lua
opts = { theme = { overrides = [your override function] } }
```

That should fix it, pretty sure 👍🏻

**Comment by OliverGuy** [comment]
That did it, much appreciated ! 🙏
