### ISSUE TITLE
New setting to set saturation level of colorscheme.

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#140]
### Question or Suggestion

Hi scottmckendry! Is it possible to include a new configuration parameter to control the saturation of the colors used for syntax highlighting similar to something which mini.hues does.

**Comment by 231tr0n** [comment]
Sure thank you for the quick response.

**Comment by 231tr0n** [comment]
Hi! I just had one suggestion. Altough I am actually able to reduce the saturation value, the white coloured part of the code is becoming way too bright. I asked this so that i can reduce the intensiveness of overall colorscheme to be easy on eyes. But i feel like white is not taking any effect here. Do you think something can be done for white as well.
![image](https://github.com/user-attachments/assets/045196fc-1aff-474f-a243-7e0991934285)

**Comment by 231tr0n** [comment]
Also i just found this out like mini.completion uses the inbuilt completion popup which is completely transparent and looks like this.
![image](https://github.com/user-attachments/assets/f7355229-27b5-41ff-84fe-dd16d73fbc3d)

**Comment by scottmckendry** [comment]
Ah, I see. Because the theme uses pure white for the `fg` colour (#ffffff), saturation actually has no effect. With a saturation value of 0, the colour will still be #ffffff. Same with a saturation of 100%, no difference. This is because saturation is a measure of colour intensity, not brightness/lightness.

What I would recommend in this case, is overriding the `fg` property via `theme.colors` in your config (see the readme for examples) with a darker colour. That should make it a bit easier on your eyes.

**Comment by 231tr0n** [comment]
One last request I am also adding it here since I did not want to create new issue again.
So i have two splits open and in transparent mode there is really no way to tell which one I am currently in.
![image](https://github.com/user-attachments/assets/2e830de7-9f9c-494a-87eb-d78fa016ffae)
I have a suggestion here as well, Can the winbar of the current split be colored the same as tabline by default.

**Comment by scottmckendry** [comment]
> Also i just found this out like mini.completion uses the inbuilt completion popup which is completely transparent and looks like this. Are you fine with adding a background to the default completion popup. 

As far as I'm aware, built-in completion use the `Pmenu` highlight group. So you could probably do something like this in your config to make it a solid colour:

```lua
            require("cyberdream").setup({
                theme = {
                    overrides = function(colours)
                        return {
                            Pmenu = { bg = colours.bg_solid },
                        }
                    end,
                },
            })
```



> I have a suggestion here as well, Can the winbar of the current split be colored the same as tabline by default and the winbar of the non current split be set transparent.

I'm not sure what you're asking here. Can you provide a bit more information on what it is you want to achieve?

**Comment by 231tr0n** [comment]
> > Also i just found this out like mini.completion uses the inbuilt completion popup which is completely transparent and looks like this. Are you fine with adding a background to the default completion popup. 
> 
> As far as I'm aware, built-in completion use the `Pmenu` highlight group. So you could probably do something like this in your config to make it a solid colour:
> 
> ```lua
>             require("cyberdream").setup({
>                 theme = {
>                     overrides = function(colours)
>                         return {
>                             Pmenu = { bg = colours.bg_solid },
>                         }
>                     end,
>                 },
>             })
> ```
> 
> 
> 
> > I have a suggestion here as well, Can the winbar of the current split be colored the same as tabline by default and the winbar of the non current split be set transparent.
> 
> I'm not sure what you're asking here. Can you provide a bit more information on what it is you want to achieve?

To brief up, there is no way currently to differentiate between a split which is active and split which is inactive without looking at the cursor. So my request is if there can be some differentiator to tell which split is active provided there are lot splits. One such thing could be the winbar.

**Comment by scottmckendry** [comment]
Thanks for the explanation. What plugin are you using in the winbar? Perhaps I could try and add support for it. 

There are some plugins that already do similar things. [Tint.nvim](https://github.com/levouh/tint.nvim), for example.

**Comment by 231tr0n** [comment]
> Thanks for the explanation. What plugin are you using in the winbar? Perhaps I could try and add support for it. 
> 
> There are some plugins that already do similar things. [Tint.nvim](https://github.com/levouh/tint.nvim), for example.

I meant highlighting Winbar and WinbarNC differently would do the job since most plugins just depend on those. I wrote custom winbar which shows symbols using trouble.nvim's statusline component.

**Comment by scottmckendry** [comment]
> Also like current mini.completion is not usable at all without this PMenu highlighting. Do you think a change to PMenu highlighting could be included when mini.completion is enabled or detected. I overrided the highlight as you mentioned but just wanted to what is your opinion on this.

My preference is bordered windows over solid backgrounds. This is how I had configured nvim-cmp and is how I've configured blink.cmp (my current completion solution).

![image](https://github.com/user-attachments/assets/f64d3316-4ca2-4177-a569-555edf840444)

However, built-in completions don't currently support borders (see the [mini.completion issue](https://github.com/echasnovski/mini.nvim/issues/1266) and the PR in nvim [here](https://github.com/neovim/neovim/pull/25541)). Hopefully, this will be available in a future release of neovim.

> highlighting Winbar and WinbarNC differently

Done. I've changed the fg property of the current window's winbar. Probably not exactly what you were after but you can override to your heart's content in the same way you've overrriden `Pmenu` by setting `WinBar` and `WinBarNC` respectively.

**Comment by 231tr0n** [comment]
> > Also like current mini.completion is not usable at all without this PMenu highlighting. Do you think a change to PMenu highlighting could be included when mini.completion is enabled or detected. I overrided the highlight as you mentioned but just wanted to what is your opinion on this.
> 
> My preference is bordered windows over solid backgrounds. This is how I had configured nvim-cmp and is how I've configured blink.cmp (my current completion solution).
> 
> ![image](https://private-user-images.githubusercontent.com/39483124/377582768-f64d3316-4ca2-4177-a569-555edf840444.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMDM4MTYsIm5iZiI6MTcyOTIwMzUxNiwicGF0aCI6Ii8zOTQ4MzEyNC8zNzc1ODI3NjgtZjY0ZDMzMTYtNGNhMi00MTc3LWE1NjktNTU1ZWRmODQwNDQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDIyMTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiZmI3ODYwNTVlNzFhYzY2ZWRjYjdiZmMzZWQ2ZDdkYWE1OTk2ZGU3NTVjZTc0YmUzZDM2YjQ3YzY5NWI1NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mSvF4aN7cXVwMQkKCZ2ynyyd_G2LiyRegqtIeQDxmZQ)
> 
> However, built-in completions don't currently support borders (see the [mini.completion issue](https://github.com/echasnovski/mini.nvim/issues/1266) and the PR in nvim [here](https://github.com/neovim/neovim/pull/25541)). Hopefully, this will be available in a future release of neovim.
> 
> > highlighting Winbar and WinbarNC differently
> 
> Done. I've changed the fg property of the current window's winbar. Probably not exactly what you were after but you can override to your heart's content in the same way you've overrriden `Pmenu` by setting `WinBar` and `WinBarNC` respectively.

Hi i just tested these changes out, i meant not changing fg but bg of winbar and setting it to be the same as tabline bg. This way it becomes one way to differentiate is what i felt.
