### ISSUE TITLE
Yazi: Low contrast in Yazi cyberdream dark theme

### ISSUE THREAD

**Issue by hankertrix** [scottmckendry/cyberdream.nvim#142]
### Description

![image](https://github.com/user-attachments/assets/f63a20cc-8107-46fd-9c8a-f20d057e20df)
![image](https://github.com/user-attachments/assets/7e11a4ed-5b59-40c7-939c-29e0f02d4418)

It's very difficult to see the number of selected items and the selected item in the completion menu.

I am using the Cyberdream dark theme for Kitty as well.

### Neovim version?

NA

### What should happen?

I should be able to easily see the text.

### What happened instead?

I am not able to easily see the text.

### Your configuration

```Lua
NA
```

**Comment by scottmckendry** [comment]
Thanks @hankertrix 

I've fixed that and refactored the config file quite a bit in the process. Should look much better now on the latest commit. 

Cheers!
