### ISSUE TITLE
Color readability issues with blink.cmp

### ISSUE THREAD

**Issue by radutomy** [scottmckendry/cyberdream.nvim#143]
### Description

I'm using cyberdream with blink.cmp https://github.com/Saghen/blink.cmp
however, I'm having issues in terms of color readability.

![image](https://github.com/user-attachments/assets/a7d93064-8264-4f08-ad4f-3fc7e4b1a91b)
![image](https://github.com/user-attachments/assets/6d980496-8f1c-487a-bcf8-7ee3dc3ded62)

While I can manually override `BlinkCmpMenu` and `BlinkCmpDoc`, I would prefer if the colors were readable out of the box. I have no issues with this exact configuration if using `nvim-cmp`

### Neovim version?

0.10.2

### What happened instead?

.

### Your configuration

```Lua
"scottmckendry/cyberdream.nvim",
lazy = false,
priority = 1000,
config = function()
	require("cyberdream").setup({
		theme = {
			overrides = function(colors)
				return {
					Comment = { fg = colors.grey, bg = "NONE", italic = true }, -- Grey color for comments
					Keyword = { fg = colors.blue, bg = "NONE" }, -- Blue for keywords
					String = { fg = colors.orange, bg = "NONE" }, -- Orange for strings
					Type = { fg = "#4EC9B0", bg = "NONE" }, -- Teal for types
					Function = { fg = "#A53FD6", bg = "NONE" }, -- Purple for functions
				}
			end,
		},
	})
end,
```

**Comment by scottmckendry** [comment]
Can I recommend using borders? I've been using cmp like this for a while now:

![image](https://github.com/user-attachments/assets/bf152abe-cdf7-4f70-8da5-42027f0396d0)

Here's my blink.cmp config:

```lua
return {
    "saghen/blink.cmp",
    dev = true,
    lazy = false,
    dependencies = "rafamadriz/friendly-snippets",
    build = "cargo build --release",
    config = function()
        require("blink.cmp").setup({
            keymap = {
                accept = "<C-y>",
                select_next = "<C-n>",
            },
            windows = {
                autocomplete = { border = "rounded", draw = "reversed" },
                documentation = { border = "rounded", auto_show = true },
                signature_help = { border = "rounded" },
            },
        })
    end,
}
```

**Comment by idelice** [comment]
I have the same issue:

https://github.com/scottmckendry/cyberdream.nvim/issues/144 

The colors are plain. White. Nothing like when using nvim-cmp.

Is this intended behavior?

**Comment by scottmckendry** [comment]
I may be wrong, but I think the issue here is slightly different. If someone wants to give me an example of what sensible defaults should be, I may consider updating them in main. But as of right now, the defaults are just fine for my use case.

**Comment by idelice** [comment]
> I may be wrong, but I think the issue here is slightly different. If someone wants to give me an example of what sensible defaults should be, I may consider updating them in main. But as of right now, the defaults are just fine for my use case.

https://github.com/scottmckendry/cyberdream.nvim/issues/144
