### ISSUE TITLE
Seems like highlights are not applied to blinkcmp

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#144]
### Question or Suggestion

This is how blinkcmp looks like when autocompletion window opens. Everything is plain white.

I confirmed that `extension.blinkcmp` is set to `true` per default, so i haven't changed any config.

Am I missing something before the theme is applied?

<img width="681" alt="Screenshot 2024-10-22 at 14 56 00" src="https://github.com/user-attachments/assets/8bc25d3c-59fc-4ecf-9245-505ad33fe987">

**Comment by scottmckendry** [comment]
As far as I'm aware you can only assign a single highlight group to the completion label (the white text you're referring to) so this might be a limitation of the plugin.

Out of curiosity, how did this look with nvim-cmp?

**Comment by scottmckendry** [comment]
Ah, I see. blink.cmp has a highlight group for matches but it's currently unused:
https://github.com/Saghen/blink.cmp/blob/b35a559abea64a1b77abf69e8252ab5cd063868a/README.md?plain=1#L119

It's already set in cyberdream.nvim so when support is added it should start working.
