### ISSUE TITLE
Can't see Quickfix selected file name

### ISSUE THREAD

**Issue by letieu** [scottmckendry/cyberdream.nvim#17]
<img width="572" alt="Screenshot 2024-04-28 at 12 58 13 AM" src="https://github.com/scottmckendry/cyberdream.nvim/assets/53562817/3a083c05-a8c6-4498-a766-1bd9868fba3e">

This colorscheme is awesome, I was update my config, but found a small issue with quickfix.

**Comment by scottmckendry** [comment]
Should look a lot better now 🙁 thanks for raising
