### ISSUE TITLE
Transparent background in Telescope?

### ISSUE THREAD

**Issue by chase-dwelle** [scottmckendry/cyberdream.nvim#24]
Love the theme! I've tried this on two machines now and notice that the Telescope background is not transparent. I'm not sure if this is by design or not, since the LazyGit background is transparent, and it is also a supported plugin. Should there be configuration changes needed to make Telescope background transparent? I'm using almost LazyVim defaults with the only change to my Telescope config being the following:

```lua
  {
    "nvim-telescope/telescope.nvim",
    -- opts will be merged with the parent spec
    opts = {
      defaults = {
        file_ignore_patterns = { ".git/", "node_modules", "poetry.lock" },
        vimgrep_arguments = {
          "rg",
          "--color=never",
          "--no-heading",
          "--hidden",
          "--with-filename",
          "--line-number",
          "--column",
          "--smart-case",
          "--trim",
        },
      },
      extensions = {
        fzf = {},
        live_grep_args = {},
      },
    },
  }
```

<img width="1742" alt="image" src="https://github.com/scottmckendry/cyberdream.nvim/assets/9752548/d8194c5a-f7d7-4972-87b6-06634366ce6a">

**Comment by scottmckendry** [comment]
You'll want to update the `borderless_telescope` property in your cyberdream config. Setting it to `false` should make telescope's float transparent.

**Comment by chase-dwelle** [comment]
Easy enough, thanks!
