### ISSUE TITLE
Search and replace with /gc needs work

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#25]
When I try to search and replace: `:%s/old/new/gc` - all texts with "old" are highlighted as usual _but_ the current "old" text is no different which means I have no idea which current "old" text i want to replace or not.

<img width="551" alt="Screenshot 2024-04-30 at 10 46 02" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/9335957e-100e-4b35-8c32-5a85be17dd79">

The second highligted text should be of different color because that's the current one.

I'm using LazyVim Distro if that helps.

**Comment by scottmckendry** [comment]
Great spotting! I've fixed this in the latest commit. Should now look like this:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/5da2f070-e2ba-4736-a23f-2da47095b1e9)
