### ISSUE TITLE
Cursorline is nonexistent

### ISSUE THREAD

**Issue by VelaSam** [scottmckendry/cyberdream.nvim#27]
The cursor line seems to be not apparent despite `vim.opt.cursorline = true`. Its not an error with my config it only happens when the cyberdream theme is selected

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/93353011/b36dda8e-e5ed-4a62-b83b-e1817a64aff8)
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/93353011/d618b475-e575-4291-9202-bd48c3a7d573)

pictures for comparison

Great theme btw, have been using it everyday since I saw the post on reddit

**Comment by scottmckendry** [comment]
Thanks for raising. I'm glad you're enjoying it!

I'll take a look into this today. I think from memory I set it to the same colour as the background mainly so it wouldn't clash with highlighted text in visual mode. It's clear to me now that these should be two different colours.

**Comment by scottmckendry** [comment]
Fixed in 1.21 🙂 
It's subtle, but it's there:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/e694317d-6337-4c51-a6ea-4c28847736c3)
