### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by sandeshkatakam** [scottmckendry/cyberdream.nvim#30]
I am currently using kickstart.nvim and a beginner to the neovim world and I am fascinated with this config. Can you help me out on how to install this? I have been trying to use the instructions you provided in my init.lua but that doesn't seem to work. It will be really great if you can provide additional directions for installation in the README.md or comment on this issue. 

Thank you

**Comment by scottmckendry** [comment]
Welcome to the rabbit hole my friend!

If you're running stock-standard kickstart.nvim, you'll want to replace [these lines](https://github.com/nvim-lua/kickstart.nvim/blob/b7d5cc8f426e1e3b6c52f79cbb2d1b3f81e7f31c/init.lua#L776C3-L792C5) with the following:

```lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            -- Recommended - see "Configuring" below for more config options
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,
            borderless_telescope = true,
            terminal_colors = true,
        })
        vim.cmd("colorscheme cyberdream") -- set the colorscheme
    end,
}
```
And it should work. However, if it's still not working and/or you're config differs wildly from kickstart, please [create a gist](https://gist.github.com/) with your full config and share it here. I will be happy to help debug 🙁

**Comment by sandeshkatakam** [comment]
Hey, Thanks for response. I have edited the following lines from my standard kickstart-nvim init.lua. However the colorscheme remains some grey rather than the one mentioned in the README.md . Should I have to download some files or is it some problem with my terminal window ?

**Comment by scottmckendry** [comment]
Hmmm... can you share the full file so I can take a look?

Do any other plugins load when you start neovim?

**Comment by sandeshkatakam** [comment]
I uploaded my .config/nvim files to this github repo: 
[https://github.com/sandeshkatakam/kickstart.nvim](url)
Can you check from here?

**Comment by sandeshkatakam** [comment]
Hey, I followed these instructions. It started working. Something clashing with my previous config I guess was the issue before.  Thanks for the help. Really appreciate it. 
Also one last doubt, where should I put the configuration code that you mentioned in the readme.md. In a separate file?

**Comment by scottmckendry** [comment]
To get transparency to work in neovim, your terminal must already be transparent. I suggest you look up whatever terminal you're using to see if:

1. It supports transparency
2. How to configure it to your liking.
