### ISSUE TITLE
Bold/Italics (and combined) in Markdown

### ISSUE THREAD

**Issue by zan-preston** [scottmckendry/cyberdream.nvim#32]
I was wondering about enabling Markdown to render strings appropriately that are in italics, bold, bold/italics? Is there a way to configure this currently (I wasn't seeing one but I could have missed it) or how hard would it be to add that in? 

I love what this theme does for styling headers and I see that it bolds them already, but getting that added to strings with emphasis would really help, especially when `conceal` is enabled so I'm not seeing it unless my cursor is on that line.

Example strings
```
*italics string*
**bold string**
***bolded italics string***
```

**Comment by scottmckendry** [comment]
Interestingly, this already works for me. See in this example markdown file:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/81172cf7-f948-4bf4-8a82-eb13f5212049)

I am using the `markdown` and `markdown_inline` treesitter parsers which I think is where this is coming from:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/75256d38-5863-4258-b96d-0bf591793aa0)

Try running `:TSInstall markdown` and `:TSInstall markdown_inline` to see if it makes any difference.

**Comment by zan-preston** [comment]
Odd. I have both of those installed (and just reinstalled, with no difference). I don't think it has to do with my font. There are some other colorschemes where this appears to work.

Could I be missing a config option for cyberdream? Or should this be default behavior?

**Comment by zan-preston** [comment]
For example, the `kanagawa.nvim` theme renders as expected. 

If more info is helpful for debugging, I'm on MacOS, using Wezterm for my terminal emulator, `JetBrainsMonoNL NF` for my font, and LazyVim for the base of my neovim config.

**Comment by zan-preston** [comment]
Also (sorry for polluting your notifications), if there's more I can do to help debug, let me know. I'm not very familiar with Treesitter objects and queries and whatnot, but I'm ready to learn :)

**Comment by zan-preston** [comment]
🙌 Thank you!!
