### ISSUE TITLE
Alacritty and Zellij support

### ISSUE THREAD

**Issue by S1M0N38** [scottmckendry/cyberdream.nvim#33]
Hi,

I prefer to maintain consistent color schemes across my terminal applications. Below are the color schemes derived from Cyberdream for Alacritty (a terminal emulator) and Zellij (a terminal multiplexer):

- [Alacritty Color Scheme](https://github.com/S1M0N38/dotfiles/blob/1f92236771606bd749d2be1d510ba9587ee984a4/config/alacritty/cyberdream.toml)
- [Zellij Color Scheme](https://github.com/S1M0N38/dotfiles/blob/1f92236771606bd749d2be1d510ba9587ee984a4/config/zellij/themes/cyberdream.kdl)

It might be beneficial to provide users with an official version of the Cyberdream color scheme for various terminal applications, similar to what is done with Catpuccin.

**Comment by scottmckendry** [comment]
Thanks for the suggestion 🙂 
I get a 404 when trying to follow the links to your config files. Maybe the repo is private? Can I suggest sharing them in a [gist](https://gist.github.com) instead?

I would love to add a Zellij theme to the growing list of extras in the repo. An Alacritty theme is already available in the[ extras directory.](https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/alacritty_cyberdream.toml)

**Comment by S1M0N38** [comment]
I'm sorry, I thought the repo was public. I've now changed its visibility.

**Comment by scottmckendry** [comment]
Thanks I can see both files now. Looks good to me!
Would you be interested in submitting a pull request to add the Zellij theme?

**Comment by S1M0N38** [comment]
I'd like to test a little bit more because there are some colors that look slightly off. I'll push soon a PR.
