### ISSUE TITLE
Highlights for nvim-treesitter/nvim-treesitter-context

### ISSUE THREAD

**Issue by sportshead** [scottmckendry/cyberdream.nvim#34]
Currently, `NormalFloat` is set to the normal fg/bg colours. This causes nvim-treesitter-context lines not to be highlighted:
> # Appearance
> Use the highlight group `TreesitterContext` to change the colors of the context. Per default it links to `NormalFloat`.

*from ([nvim-treesitter/nvim-treesitter-context README](https://github.com/nvim-treesitter/nvim-treesitter-context?tab=readme-ov-file#appearance))*

<details>
<summary>lazy config</summary>

```lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    opts = {
        transparent = true,
        italic_comments = true,
        hide_fillchars = true,
        borderless_telescope = false,
        terminal_colors = true,

        theme = {
            highlights = {
                LineNr = { fg = "#5C6594" },
            },
        },
    },
    config = function(_, opts)
        require("cyberdream").setup(opts)
        vim.cmd("colorscheme cyberdream")
    end,
},
```
</details> 

## Screenshots
current cyberdream: 
![cyberdream screenshot](https://i.sportshead.dev/vb2qal4.png)

tokyonight:
![tokyonight screenshot](https://i.sportshead.dev/d1wcexo.png)

**Comment by scottmckendry** [comment]
Thanks for the detailed issue! I've added highlights for treesitter context in the latest commit. Now looks like this:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/11bb15c9-b4fd-4fc5-bd30-1445bb850609)

Gone for something bold with the dark cyan - hope you like it!

**Comment by sportshead** [comment]
Looks great, thanks!
