### ISSUE TITLE
Feedback for Improvement

### ISSUE THREAD

**Issue by scottmckendry** [scottmckendry/cyberdream.nvim#4]
Hello @ianchesal 

I  came across a recent commit to your dotfiles repo via GitHub search this morning that caught my interest:

https://github.com/ianchesal/dotfiles/commit/329fa7831a0e479d8b0e102081f12d9c100da6f7

I was wondering if I could get your thoughts and feedback. Is there anything you feel was missing from the colour scheme? Anything you would change or not quite right?

Appreciate your time! 

Cheers,
Scott

**Comment by ianchesal** [comment]
Oh hey. This is...uh...very direct!

The biggest issue, for me, was the default colour and styling on the mini-tabline.nvim bars. The pink tabline bar was too much for what I need. Garish? Overly prominent for the active indent level? 

And for strings, a more muted option other than lime green would be nice. In string-heavy files it got pretty green.

Styling on Telescope windows also seemed possibly broken? Here's what I see with cyberdream:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/291808/fb6b577d-ef46-4175-979a-e0ae11e42f14)

Versus Tokyo Night:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/291808/d48f7f42-c3dc-4305-acf9-595d05d40eb0)

The blocking on the modal in Tokyo Night definitely makes it feel a little more polished, to me.

Hope that helps!

Like I said, I'll keep an eye on it. The Philip K. Dick'ness of it was appealing. Just need a scan to tell if I'm a replicant or not before I can edit files, maybe?

**Comment by ianchesal** [comment]
Oh. Maybe I should try `hide_fillchars = false`?

**Comment by scottmckendry** [comment]
This is excellent feedback! Thank you very much.

The telescope theming is intentional, as I'm not much of a fan of the bordered look that it ships with. That being said, it looks slightly better with the tweaks I have in [my config](https://github.com/scottmckendry/Windots/blob/main/nvim/lua/plugins/telescope.lua):

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/0eb52848-b36d-4a31-b119-b2a59c2dc23f)

I'll add an option to toggle the "borderless" look. I'll also add an option to override specific highlight groups (like "String"). I'm thinking something similar to how [Kanagawa does it](https://github.com/rebelot/kanagawa.nvim?tab=readme-ov-file#customization).

Thanks again for the suggestions! Updates coming soon 🚀

**Comment by scottmckendry** [comment]
@ianchesal I've merged the changes into main. I've included and example config below that _should_ address some or all of the issues you raised. 

```lua
require("cyberdream").setup({
    transparent = true,
    italic_comments = true,
    hide_fillchars = true,
    borderless_telescope = false, -- more default-looking telescope

    theme = {
        colors = {
            -- Use a slightly darker green
            green = "#06c258",
        },

        highlights = {
            -- Set indent scope to blue (instead of pink)
            MiniIndentScopeSymbol = { fg = "#5ea1ff" },
        },
    },
})
```

**Comment by ianchesal** [comment]
@scottmckendry I'll check it out today.

I should say: you shouldn't do things based on one person's feedback, especially mine! I'm chuffed you did this, but don't sweat my notes. I'm nobody and this is your theme.

Thanks!
