### ISSUE TITLE
Support more plugins

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#42]
### Question or Suggestion

Hi, I love your theme. It really works well and I would suggest adding support to more plugins:

* Aerial
* mini-files
* Grapple
* LazyGit
* LazyDocker

**Comment by scottmckendry** [comment]
Thanks for the suggestion! I'll put these on the to-do list.

**Comment by idelice** [comment]
Hi @scottmckendry 

Is there a way to also support TUI like Neovide? 

Using Neovide, the telescope UI looks very messy with the borders.

<img width="1499" alt="Screenshot 2024-05-20 at 11 19 01" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/9eba9901-c0a9-413c-b9f7-814346378d91">

Compared to neovim:
<img width="1493" alt="Screenshot 2024-05-20 at 11 19 31" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/dc6888dd-fdbd-4cd9-8a8c-2dd0d913953c">

**Comment by scottmckendry** [comment]
Thanks @idelice 🙂 I've opened a new issue for Neovide support (#54).

**Comment by scottmckendry** [comment]
I finally had a chance to return to this one and review support for the remaining plugins. What's left should look pretty good with the default linked groups.

I've added explicit support for:
- Grapple
- Minifiles
- Lazygit (via extra)
- Lazydocker (via extra)

If any highlights are missing or not quite right, I suggest adding overrides for these as shown in the readme/docs.
