### ISSUE TITLE
bug lazydocker: having cursor on an item makes the name unreadable

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#43]
### Description

When I navigate to an item, the item name becomes unreadable
<img width="483" alt="Screenshot 2024-05-09 at 23 36 32" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/0475004d-22b7-411c-a092-737c4761c515">
<img width="487" alt="Screenshot 2024-05-09 at 23 36 37" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/daf13a0f-6114-493f-ab04-d0c0c36fe417">
<img width="474" alt="Screenshot 2024-05-09 at 23 36 43" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/fe75dea3-3f4d-4514-8a1d-e727382d1f40">
<img width="474" alt="Screenshot 2024-05-09 at 23 36 47" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/525e5c94-fa1e-4e2b-8bba-b665a654ccce">

### Neovim version?

0.9.4

### What should happen?

The highlighted text when cursor is on that item should be readable

### What happened instead?

It becomes unreadable

### Your configuration

```Lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,
            borderless_telescope = true,
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

**Comment by scottmckendry** [comment]
Check your lazydocker config file at `~/.config/lazydocker/config.yml`. I suspect that blue colour is coming from your theme property.

There's a theme config here that you can try to see if it makes any difference:
https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/lazydocker/cyberdream.yml

Also try running `lazydocker` outside of neovim - just to see if it makes any difference.

**Comment by idelice** [comment]
<img width="512" alt="Screenshot 2024-05-10 at 20 53 44" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/8c65189a-935e-4ce4-9e59-d01090e0b4a9">

that is from running lazydocker outside neovim. there's clearly a difference.

I don't have ny lazydocker config for theming

**Comment by idelice** [comment]
Applied that config you've mentioned fixed it for me. thanks
