### ISSUE TITLE
bug: "light" theme makes cursor invincible

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#47]
### Description

Enabling "light" theme causes cursor to be invincible

### Neovim version?

0.9.4

### What should happen?

The cursor should be *visible*

### What happened instead?

It became invincible

### Your configuration

```Lua
return {
  "scottmckendry/cyberdream.nvim",
  lazy = false,
  priority = 1000,
  config = function()
    require("cyberdream").setup({
      -- Recommended - see "Configuring" below for more config options
      -- transparent = true,
      italic_comments = true,
      hide_fillchars = true,
      borderless_telescope = true,
      terminal_colors = true,
      theme = {
        variant = "light",
        highlights = {
          Type = { fg = "NONE", bg = "NONE" },
        },
      },
    })
    vim.cmd("colorscheme cyberdream") -- set the colorscheme
  end,
}
```

**Comment by scottmckendry** [comment]
Thanks @idelice 
Any chance you can add a screenshot to show the problem?

May I also ask which terminal you're using? If it's one of the ones that has an extra in the cyberdream repo, can you try using the light version of the config?

E.g. [alacritty](https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/alacritty/cyberdream-light.toml), [wezterm](https://github.com/scottmckendry/cyberdream.nvim/blob/main/extras/wezterm/cyberdrea-light.lua)

If you're still using a dark theme in your terminal, it won't play nicely with light, transparent cyberdream.

**Comment by idelice** [comment]
I'm using Kitty and that may be why it looks so different from this guy who is using wezterm: https://www.reddit.com/r/neovim/comments/1cp8833/can_light_themes_be_pretty/#lightbox 

Any chance you can add support for Kitty?

This is how it looks like in my Kitty terminal lol

<img width="509" alt="Screenshot 2024-05-13 at 21 45 21" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/bcd05a8f-0fe8-4c7a-b3fa-31b17c9e7f67">

**Comment by scottmckendry** [comment]
Ah I see... yes, have just added a new extra for kitty here:

https://github.com/scottmckendry/cyberdream.nvim/blob/kitty-extra/extras/kitty/cyberdream-light.conf

Give it a spin. Keen to see how it looks :)

**Comment by idelice** [comment]
It looks better now, but I have few feedback items:

1. the selected cursor text should have a different color to show the character at the cursor. Right now, it's completely black.
2. better contrast for the characters. right now, it seems a bit hard to see the words e.g. "public class"
3. it's hard to notice mini.files' borders
4. which-keys' "red" characters could use better contrast 
5. lualine showing the current buffer name could use better contrast
... in general, it works, but contrast needs to be adjusted when using light mode. 

But, great job! I appreciate it

<img width="568" alt="Screenshot 2024-05-13 at 22 33 24" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/c1aaa58e-fead-47de-8785-c2286c051f19">

<img width="776" alt="Screenshot 2024-05-13 at 22 36 26" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/1aee21c8-98c2-4e13-bb77-9d1b3259f12d">
<img width="259" alt="Screenshot 2024-05-13 at 22 38 15" src="https://github.com/scottmckendry/cyberdream.nvim/assets/59118341/c5845c38-cac6-4b33-b610-a130b08e4b15">

**Comment by scottmckendry** [comment]
Great feedback! Thank you.

1. Should now be addressed. I've added the cursor_text_color property to the [kitty theme](https://github.com/scottmckendry/cyberdream.nvim/blob/kitty-extra/extras/kitty/cyberdream-light.conf).
2. This is subjective, but I can see what you mean from the screenshot. I'd suggest overriding the orange color in your config.
3. Also subjective. I like the minimal borders in mini.files as is. But understand it's not for everyone. You can override the highlight group in your config. Specifically the `MinifilesBorder` group. 
4. See 2 😉 
5. Lualine might still be running the dark theme. You'll need to update your lualine config to require the light variant instead. E.g. `require("lualine.themes.cyberdream-light")`. Hopefully that will help!
