### ISSUE TITLE
It's possible configure in Packer?

### ISSUE THREAD

**Issue by daltondiaz** [scottmckendry/cyberdream.nvim#50]
### Question or Suggestion

Hi everyone,

I'll like to use this awesome theme, but current I use Packer to manager my plugins, so trying to do that don't work:

packer.lua
```lua
    use {
        'scottmckendry/cyberdream.nvim',
        lazy = false,
        priority = 1000
    }
```

after/plugin/colors.lua
```lua
require("cyberdream").setup({
    -- Enable transparent background
    transparent = true, -- Default: false

    -- Enable italics comments
    italic_comments = true, -- Default: false

    -- Replace all fillchars with ' ' for the ultimate clean look
    hide_fillchars = true, -- Default: false

    -- Modern borderless telescope theme
    borderless_telescope = true, -- Default: true

    -- Set terminal colors used in `:terminal`
    terminal_colors = true, -- Default: true

    theme = { -- Default: nil
        variant = "light", -- Default: "deafult" (dark)
        highlights = {
            -- Highlight groups to override, adding new groups is also possible
            -- See `:help highlight-groups` for a list of highlight groups

            -- Example:
            Comment = { fg = "#696969", bg = "NONE", italic = true },

            -- Complete list can be found in `lua/cyberdream/theme.lua`
        },

        -- Override a color entirely
        colors = {
            -- For a list of colors see `lua/cyberdream/colours.lua`
            -- Example:
            bg = "#000000",
            green = "#00ff00",
            magenta = "#ff00ff",
        },
    },
})
```
Result: 
![2024-05-15_14-43](https://github.com/scottmckendry/cyberdream.nvim/assets/3844467/c3f67358-4d83-44bb-8568-9a52ac815706)

I use the default and most simple configuration, maybe losing something in the config.

Thanks!!

**Comment by daltondiaz** [comment]
Sorry, but I made work partial

I add this function in my `after/plugin/colors`

```lua
function ColorMyPencils(color)

    color = color or "cyberdream"
    vim.cmd.colorscheme(color)

end
ColorMyPencils()
``` 

the result was 

![2024-05-15_14-58](https://github.com/scottmckendry/cyberdream.nvim/assets/3844467/9f4dea6c-2884-401a-8be3-c0afc7975e79)

but telescope continues not working in transparent mode
![2024-05-15_15-05](https://github.com/scottmckendry/cyberdream.nvim/assets/3844467/ec83cdbe-1f4e-4cc2-9db3-a93eb92538ed)

**Comment by scottmckendry** [comment]
Thanks @daltondiaz 🙂 
I'll get some Packer install instructions added to the readme. 

Telescope looks correct based on your configuration. You can set `borderless_telescope` to `false` in your config to make the window transparent.

**Comment by daltondiaz** [comment]
@scottmckendry perfect!!!

Everything working, thanks!!

![2024-05-15_16-16](https://github.com/scottmckendry/cyberdream.nvim/assets/3844467/75146a91-85b0-402f-9049-eda16dbb0ce6)
