### ISSUE TITLE
Request: change LineNr color

### ISSUE THREAD

**Issue by EderLukas** [scottmckendry/cyberdream.nvim#52]
Hi, I would like to ask if it is possible to change the LineNumber Color away from bgHighlight?
Reason is, the line numbers are very thin and you can see them best with very high contrasts like black and white for example. In order to see the highlighted text, highlights needs to be darker then the text but brighter then the background which gives that colorgrade in which the thin linenumbers get hard to see (at least for me).

Otherwise, I really like the theme! Thank you for the great work!

**Comment by scottmckendry** [comment]
Glad you like the theme! Thanks for the feedback, I've brightened this highlight slightly in the most recent commit.

In case it's not quite as high-contrast as you were hoping, you can override specific highlight groups and their colours directly in your config.

For example:
```lua
{
    "scottmckendry/cyberdream.nvim",
    lazy = false,
    priority = 1000,
    config = function()
        local colors = require("cyberdream.colors").default
        require("cyberdream").setup({
            transparent = true,
            italic_comments = true,
            hide_fillchars = true,

            theme = {
                highlights = {
                    LineNr = { fg = colors.magenta },
                },
            },
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

Will look like this:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/a6dda82f-5a77-47a0-ab73-ffea9db1047f)

Let me know if you have any questions!

**Comment by EderLukas** [comment]
phenomenal! thank you very much!!
