### ISSUE TITLE
Easy way to switch theme variant?

### ISSUE THREAD

**Issue by oversoul** [scottmckendry/cyberdream.nvim#53]
### Question or Suggestion

Hello,
really Thank you for the theme!

I'm wondering if there is a simple way to switch the theme variant.

maybe using `set background=light`

**Comment by scottmckendry** [comment]
Thanks for the suggestion! I've implemented this in the [light-dark-toggle](https://github.com/scottmckendry/cyberdream.nvim/tree/light-dark-toggle) branch. You can try it out by adding the `branch` option to your config (if you're using lazy). 

```lua
return {
    "scottmckendry/cyberdream.nvim",
    branch = "light-dark-toggle",
    lazy = false,
    priority = 1000,
    config = function()
        require("cyberdream").setup({
            transparent = false,
            italic_comments = true,
            hide_fillchars = true,
        })
        vim.cmd("colorscheme cyberdream")
    end,
}
```

To toggle between light & dark modes, run `:CyberdreamToggleMode`. 

If you're using Lualine, its theme will also be swapped. Let me know if this is what you had in mind!

**Comment by oversoul** [comment]
Thank you @scottmckendry that's exactly what I had in mind.
I'm not using lualine, but the theme variant swap works fine.
Thank you again!
