### ISSUE TITLE
Error after update 

### ISSUE THREAD

**Issue by muzichen** [scottmckendry/cyberdream.nvim#67]
### Description

Today I just update the cyberdream colorscheme, and it tells me it has break changes. When I restart nvim there is an error message like this:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/7547416/e71976bf-027d-400b-8f6b-0826cf8cfe8c)

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/7547416/aacc3733-eadd-4c29-a9dd-6326c6cc2487)

And I use lazy.vim.

### Neovim version?

0.10.0

### What should happen?

No Error message.

### What happened instead?

Error message is showed.

### Your configuration

```Lua
return {
  "scottmckendry/cyberdream.nvim",
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "cyberdream",
    },
  }
}
```

**Comment by catoa** [comment]
I ran into this as well with my lazyvim config and was able to resolve it by updating my lualine config. I now have 
```lua
return {
  ...
  {
    "nvim-lualine/lualine.nvim",
    opts = function()
      local cyberdream = require("lualine.themes.cyberdream").get_theme()
      return {
        options = {
          ...
          theme = cyberdream
        }
      }
  }
```

I've redacted some things but I think this is the minimum to get this working for now.

**Comment by scottmckendry** [comment]
@muzichen thanks for raising the issue. @catoa is right. Take a look at the pinned issue #65 that has some more info on this.

This was the breaking change introduced in v2.

**Comment by scottmckendry** [comment]
Ignore my last comment and the v2 release entirely. A big mess up on my part will have broken any lualine configs using the "auto" theme. 

I've resolved this now with the v3 release. If your config working in v1 it should now work again.

**Comment by muzichen** [comment]
@scottmckendry  Thanks for your great work and thanks @catoa , it works.
