### ISSUE TITLE
[Feat]: more colour distinction

### ISSUE THREAD

**Issue by AlejandroSuero** [scottmckendry/cyberdream.nvim#69]
### Question or Suggestion

I am currently using [astrotheme](https://github.com/AstroNvim/astrotheme) but I discovered this theme and I loved it, but the problem is, that all seems the same colour, hard to distinguish the type of variables.

- cyberdream:
<img width="558" alt="cyberdream colorscheme" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/ec4f07e2-1579-4ad3-941c-e9365271233b">

- [astrotheme](https://github.com/AstroNvim/astrotheme):
<img width="558" alt="astrodark" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/b21b2591-dd65-4323-9ef8-1bc3729902b2">

- [catppuccin](https://github.com/catppuccin/nvim):
<img width="558" alt="catppuccin mocha" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/efe46915-3f38-4fbf-be0e-899caab10fb8">

- [rose-pine](https://github.com/rose-pine/neovim)
<img width="558" alt="rose-pine-moon" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/13f06aec-b4f6-4427-b44f-16d2dbfc5e23">

---

As you can see, booleans have their own colour and accessing a variable member as well.

The highlight groups affected in this group, using `:Inspect` in the other colorschemes, are:

- `@boolean.lua links to Boolean`
- `@variable.lua links to @variable`
- `@variable.member.lua links to @property`

How cyberdream is currently:

- `@boolean.lua links to Constant`
- `@variable.lua links to @variable`
- `@variable.member.lua links to @variable`

In the case that this is the intended colour palette, at least exposing a function to override or add highlights would be a good start.

**Comment by AlejandroSuero** [comment]
A little preview of adding more distinction (the palette and colours chosen can be change):

https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/9e70aff2-e52a-4888-896f-c01e12908d98

If you want me to the a PR about it @scottmckendry, with a more defined colours to use for the different scenarios, like for example this minimal change:

<img width="558" alt="Screenshot 2024-06-14 at 12 34 53" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/31b50bbb-71c9-43ee-a563-14f0c313e70f">

**Comment by AlejandroSuero** [comment]
I started doing a little override function to showcase what I meant for that, as maybe confusing having a `highlights` entry on `theme`.

<img width="558" alt="override function" src="https://github.com/scottmckendry/cyberdream.nvim/assets/71392160/90b0ec43-09d9-4a39-981d-c6ffea69486c">

The function will give you the ability to use the colour palette instead of hard coding colours.

**Comment by scottmckendry** [comment]
Thanks for raising this @AlejandroSuero !

You aren't the first one to ask for this, and I think you're right, I think we should add in a couple of new defaults to separate booleans, variables, properties etc. 

I like the look of this one here (to start):

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/e0e1c354-38e8-463b-a253-c2f6004833f8)

Are you happy to open another PR to get this rolling?

**Comment by AlejandroSuero** [comment]
@scottmckendry yeah, I can do it. Should we keep this issue open? (to include closes # (issue) or not)
