### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by fingolfin19** [scottmckendry/cyberdream.nvim#8]
Nvim is deprecating VertSplit and moving to WinSeparator for borders in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

**Comment by scottmckendry** [comment]
Thanks for the issue. Do you have some more info on the deprecation or maybe an example of where you're seeing wrong highlights? 

I've not tested cyberdream with 0.10 yet but I can confirm that the [WinSeperator group is set](https://github.com/scottmckendry/cyberdream.nvim/blob/762715ccfab2ae0078380f0c2706b2f91ffb1c23/lua/cyberdream/theme.lua#L52C13-L52C13).

**Comment by fingolfin19** [comment]
> Thanks for the issue. Do you have some more info on the deprecation or maybe an example of where you're seeing wrong highlights?
> 
> I've not tested cyberdream with 0.10 yet but I can confirm that the [WinSeperator group is set](https://github.com/scottmckendry/cyberdream.nvim/blob/762715ccfab2ae0078380f0c2706b2f91ffb1c23/lua/cyberdream/theme.lua#L52C13-L52C13).

Ah, there's a typo in your file. It's WinSeparator, not WinSeperator.

**Comment by scottmckendry** [comment]
Well, that's a bit embarrassing! I've fixed the typo in the [latest commit](https://github.com/scottmckendry/cyberdream.nvim/commit/a80be2fecf59d0c74541ac6c10f0e2f37120afde). Thanks again!

**Comment by cybergaz** [comment]
windows separation is non-existent
even after setting up `WinSeparator = { fg = "#50505e", bg = "" }`

![1714504850](https://github.com/scottmckendry/cyberdream.nvim/assets/43444535/e3756306-44b0-44d4-9909-f69233d5e2b2)

**Comment by scottmckendry** [comment]
@cybergaz there's an override for this in the config - `hide_fillchars` that sets these to `" "` when true.
https://github.com/scottmckendry/cyberdream.nvim/blob/d777f1bfb0e6e1d74b3f243d8e4999b6b931ae19/lua/cyberdream/theme.lua#L18C4-L29C9

Setting this to false will change them back to the default.

**Comment by cybergaz** [comment]
thx... that solved it

but may i ask what's the point of these hide fillchars??

**Comment by scottmckendry** [comment]
Preference. To me, fill chars are extra visual clutter. But not everyone sees it that way, which is why I added the option 😉
