### ISSUE TITLE
control brightness for the white color in the theme

### ISSUE THREAD

**Issue by 231tr0n** [scottmckendry/cyberdream.nvim#85]
### Question or Suggestion

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/56352048/f59148cb-09d0-43ca-b65e-150712d6ac43)
Are there any plans on implementing options for controlling brightness like how tokyonight.nvim does.
Altough it is just my perspective but I feel like #ffffff is way too bright for foreground. Is there any change of adding a setting to control the brightness of the white color in the theme.

**Comment by scottmckendry** [comment]
Understood @231tr0n 🙂 

The default fg color isn't for everyone. It's for this reason that cyberdream supports color overrides when calling `setup()`. 

You can get a dimmer fg color with the following config:
```lua
return {
    {
        "scottmckendry/cyberdream.nvim",
        priority = 1000,
        config = function()
            require("cyberdream").setup({
                transparent = true,
                theme = {
                    colors = {
                        fg = "#c5c8c6",
                    },
                },
            })
            vim.cmd("colorscheme cyberdream")
        end,
    },
}
```
Before:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/0fe39014-639e-4b4a-85de-03f5fcfd7176)

After:
![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/d280102a-8cdc-4752-8270-7ac2342c7d17)

Feel free to play around with the colors until you find something suitable!

**Comment by 231tr0n** [comment]
Yup this helps. I can try configuring this to suit my needs. Thank you.
