### ISSUE TITLE
Support more plugins

### ISSUE THREAD

**Issue by idelice** [scottmckendry/cyberdream.nvim#88]
I have a couple more plugins in my mind that I would like to suggest supporting:

1. Gitpad.nvim
2. Trouble.nvim
3. Curl.nvim
4. Kubectl.nvim

**Comment by scottmckendry** [comment]
Thanks for the request @idelice! I've already made a start with kubectl.nvim in the latest commit. 

I don't think I can feasibly add support for curl.nvim - I've checked the source code and it only has [one highlight group](https://github.com/oysandvik94/curl.nvim/blob/8c7e60c4624d05bbab6b62c5d36d7e95fb3848cf/lua/curl/parser.lua#L7l) defined. 

Is there something specific that looks odd when using cyberdream.nvim with this plugin?

**Comment by idelice** [comment]
> Thanks for the request @idelice! I've already made a start with kubectl.nvim in the latest commit. 
> 
> 
> 
> I don't think I can feasibly add support for curl.nvim - I've checked the source code and it only has [one highlight group](https://github.com/oysandvik94/curl.nvim/blob/8c7e60c4624d05bbab6b62c5d36d7e95fb3848cf/lua/curl/parser.lua#L7l) defined. 
> 
> 
> 
> Is there something specific that looks odd when using cyberdream.nvim with this plugin?
> 
> 
> 
> 
> 
> 

No thank you

**Comment by scottmckendry** [comment]
Support for plugins has been added in [v3.4.0](https://github.com/scottmckendry/cyberdream.nvim/releases/tag/v3.4.0) 🙂
