### ISSUE TITLE
Selection color is same as color used for some syntax highlighting

### ISSUE THREAD

**Issue by nshern** [scottmckendry/cyberdream.nvim#9]
Selection color is same as color used for some syntax highlighting, which results in some elements "disappearing" when highlighted.

Example markdown:

```markdown
# Title 1
## Title 2
### Title 3
```

When visual mode is enabled and this block is selected, you won't be able to see the contents of the third line. The same happens in this example python:

```python
def foo:
    print("bar")
```

My suggestion would be to find a color for highlighting that is not used for syntax highlighting.

**Comment by scottmckendry** [comment]
Thanks for reporting, not sure why I never noticed this. I've set it to a saner color now which should be a bit easier on the eyes too. Here's what it looks like on the latest commit:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/f932bda6-8126-4c67-acae-7eb10f573ba1)
