### ISSUE TITLE
How to transparent telescope ? 

### ISSUE THREAD

**Issue by Jchael12** [scottmckendry/cyberdream.nvim#93]
### Question or Suggestion

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/120585376/7e88e588-20ec-4853-a88a-dc54b4bcbc2c)

**Comment by scottmckendry** [comment]
Set `borderless_telescope = false` inside the `setup()` function in your config 🙂

**Comment by Jchael12** [comment]
Thank you very much ! 🙂
