### ISSUE TITLE
How can I make the builtin types italic (or different color)?

### ISSUE THREAD

**Issue by emrebengue** [scottmckendry/cyberdream.nvim#96]
### Description

I am trying to make the builtin types in italic (or different color) to be able to distinguish them better.

### Neovim version?

nvim v0.10.0

### What happened instead?

![Screenshot from 2024-07-08 17-16-36](https://github.com/scottmckendry/cyberdream.nvim/assets/78328981/da66d1f2-1c11-47de-bc2e-65bfac02a7fc)
:Inspect when the cursor is on 'int'
![Screenshot from 2024-07-08 17-11-16](https://github.com/scottmckendry/cyberdream.nvim/assets/78328981/3dec2266-c10d-44cf-816e-192f5d23c729)
and this is when the cursor is on 'int32'

#include <cstdint>
#include <stdio.h>
#include <unistd.h>
#include <stdio.h>
#include <string>

#include <assert.h>
#include <errno.h>

typedef unsigned int int32;
typedef unsigned short int int16;

### Your configuration

```Lua
return {
  "scottmckendry/cyberdream.nvim",
  lazy = false,
  priority = 1000,
  config = function()
    require("cyberdream").setup {
      transparent = true,
      italic_comments = true,
      hide_fillchars = true,
      terminal_colors = true,
      borderless_telescope = { border = false, style = "flat" },
      theme = {
        variant = "auto",
        overrides = function(colours)
          return {
            TelescopePromptPrefix = { fg = colours.blue },
            TelescopeMatching = { fg = colours.cyan },
            TelescopeResultsTitle = { fg = colours.blue },
            TelescopePromptCounter = { fg = colours.cyan },
            TelescopePromptTitle = { fg = colours.bg, bg = colours.blue, bold = true },
          }
        end,
      },
    }

    vim.cmd("colorscheme cyberdream")
    vim.api.nvim_set_keymap("n", "<leader>tt", ":CyberdreamToggleMode<CR>", { noremap = true, silent = true })
    vim.api.nvim_create_autocmd("User", {
      pattern = "CyberdreamToggleMode",
      callback = function(ev)
        print("Switched to " .. ev.data .. " mode!")
      end,
    })
  end,
}
```

**Comment by scottmckendry** [comment]
Thanks for raising, @emrebengue!

I've made some small changes to the base theme to provide a bit more distinction base on your feedback. Here is what it looks like on the latest commit:

![image](https://github.com/scottmckendry/cyberdream.nvim/assets/39483124/2bc7e761-3c92-4543-bcc9-8d15fa1e8f71)
