### ISSUE TITLE
The popup border is invisible

### ISSUE THREAD

**Issue by Stark-X** [scottmckendry/cyberdream.nvim#99]
### Question or Suggestion

Now:
![image](https://github.com/user-attachments/assets/bce0c81a-7eee-4603-bf9c-5a88b165d0ea)
Should looks like:
![image](https://github.com/user-attachments/assets/9c1f6a45-334a-4d26-ada4-42c05e39cdb5)

I'm using vim-go, when I execute `:GoDoc`, the border is invisible, how can i fix this ?

**Comment by scottmckendry** [comment]
I think I found the problem - there's no border on the window and there also doesn't appear to be any way to set the Windows highlights either. 

https://github.com/fatih/vim-go/blob/master/autoload/go/doc.vim#L129

I'm not sure there's a whole lot I can do to make this look better without affecting all other floats in Neovim. 

I would suggest looking elsewhere for go dev in Neovim, it doesn't look like this plugin is even maintained anymore.

This one here is a great option if you want something that works great out of the box:
https://github.com/ray-x/go.nvim

**Comment by Stark-X** [comment]
alright.. 
I'll try to use the go.nvim , tks a lot.

**Comment by Stark-X** [comment]
![image](https://github.com/user-attachments/assets/5fbb79d4-5b33-4436-ae59-10b2479678ca)
I found an other problem, when I open a "quickfix" pane, the border/split-line is invisible too 

![image](https://github.com/user-attachments/assets/ce3bc01f-eafa-4475-8e65-eff54aeab987)
and the also happen on the help-pane `:help vim`

**Comment by scottmckendry** [comment]
Do you have `hide_fillchars` set to `true` in your cyberdream config? If not it could be your statusline setting. We found that to be the case here:
https://github.com/scottmckendry/cyberdream.nvim/issues/81#issuecomment-2197777969

**Comment by Stark-X** [comment]
`hide_fillchars` set to `true` works !
and after switching to go.nvim + lspsaga, i found that `lsp_keymaps=false` must be set, or it will fallback to using the lsp hover function which display without border by default.
